####################################################
####  Login to generate JWT
####################################################
# curl -X 'POST'
#  'http://localhost:3000/api/auth/login'
#  -H 'accept: application/json'
#  -H 'Content-Type: application/json'
#  -d '{
#  "username": "string",
#  "password": "Abcd1234"
#}'
POST http://localhost:3000/api/auth/login
accept: application/json
Content-Type: application/json

{
  "username": "string",
  "password": "Abcd1234"
}

###



# curl -X 'POST'
#  'http://localhost:3000/api/auth/login'
#  -H 'accept: application/json'
#  -H 'Content-Type: application/json'
#  -d '{
#  "username": "string",
#  "password": "Abcd1234"
#}'
POST http://localhost:3000/api/auth/login
accept: application/json
Content-Type: application/json
Authorization: Bearer <<JWT from login>>

{
  "username": "string",
  "password": "Abcd1234"
}

###

# Create a new subscription
POST http://localhost:3000/api/subscriptions
accept: application/json
Content-Type: application/json
Authorization: Bearer <<JWT from login>>

{
  "email": "email@test.com",
  "firstName": "string",
  "dateOfBird": "1970-01-01",
  "isConsent": true,
  "newsletterId": "string"
}

###


# curl -X 'DELETE'
#  'http://localhost:3000/api/subscriptions/ID'
#  -H 'accept: application/json'
DELETE http://localhost:3000/api/subscriptions/{ID}
Authorization: Bearer <<JWT from login>>
accept: application/json

###


# curl -X 'GET'
#  'http://localhost:3000/api/subscriptions/ID'
#  -H 'accept: application/json'
GET http://localhost:3000/api/subscriptions/{ID}
Authorization: Bearer <<JWT from login>>
accept: application/json

###


# curl -X 'GET'
#  'http://localhost:3000/api/subscriptions?page=0&sizePage=1'
#  -H 'accept: application/json'
GET http://localhost:3000/api/subscriptions?page=0&sizePage=1
Authorization: Bearer <<JWT from login>>
accept: application/json

###

